name: Path-Push type Workflow

on:
  push:
    paths: '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Stage
        run: echo "Build Successfull"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build Stage
        run: echo "Testing Successfull"
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Build Stage
        run: echo "Deployed Successfully"
