name: PR comment type Workflow

on: issue_comment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Stage
        run: echo "Build Successfull"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Stage
        run: echo "Testing Successfull"
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Stage
        run: echo "Deployed Successfully"
